first_app/urls.py
from unicodedata import name
from django.conf.urls import url
from django.urls import path
from first_app import views
app_name = "first_app"


urlpatterns = [
    path('',views.index,name='index'),
    path('add_album/',views.album_form, name = 'album_form'),
    path('add_musician/',views.musician_form, name='musician_form'),
    path('album_list/<int:artist_id>/',views.album_list,name='album_list'),
   
]

project_uturn/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('first_app.urls')),
    
]

first_app/models.py
from platform import release
from django.db import models


# Create your models here.

class Musician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)
    
    def __str__(self):
        return self.first_name + "" + self.last_name + "" +self.instrument

class Album(models.Model):
    #id = models.AutoField(primary_key=True)   
    artist = models.ForeignKey(Musician,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField()
    
    rating =(
        
        (1,"Worst"),
        (2,"Bad"),
        (3,"Not Bad"),
        (4,"Good"),
        (5,"Excellent"),
        
    )
    
    num_stars = models.IntegerField(choices=rating)
    def __str__(self):
        return self.name + "Rating:"+ str(self.num_stars)
    
    
        
    
     
    

first_app/forms.py
from django import forms
from first_app import models

# class user_form(forms.Form):
    # user_name = forms.CharField(label='Full Name', widget=forms.TextInput(attrs={'placeholder':'Enter you full name'}))
    # user_email = forms.EmailField(label='User Email', widget=forms.TextInput(attrs={'placeholder':'Please,Enter your Email'}))
    
    # user_dob = forms.DateField(label='Date Of Birth',widget=forms.TextInput(attrs={'type':'date'}))
      # boolean_field = forms.BooleanField(required=False)
  #  field = forms.CharField(max_length=15, min_length=5)
  # choices = (('','--SELECT OPTION'),('1','First'),('2','Second'),('3','Third'))
  # field = forms.ChoiceField(choices=choices,required=False)
  
  # choices = (('A','A'),('B','B'),('C','C'),('D','D'))
  # field = forms.ChoiceField(choices=choices,widget=forms.RadioSelect)
  
  #  choices = (('A','A'),('B','B'),('C','C'),('D','D'))
  #  field = forms.MultipleChoiceField(choices=choices,widget=forms.CheckboxSelectMultiple)
  
class MusicianForm(forms.ModelForm):
  class meta:
    model = models.Musician
    fields = "__all__"
    
class AlbumForm(forms.ModelForm):
  class meta:
    model = models.Album
    fields = "__all__"
    
  release_date =forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))             
      
      

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Musician,Album
from first_app.forms import MusicianForm,AlbumForm
from first_app import forms


# Create your views here.

def index(request):
    musician_list = Musician.objects.order_by('first_name')
    diction = {'title':"Homepage", 'musician_list':musician_list}
    return render(request,'first_app/index.html',context=diction)
def album_list(request,artist_id):
    diction = {'title':"List of Albums"}
    return render(request,'first_app/album_list.html',context=diction)
def musician_form(request):
    form = forms.MusicianForm()
    if request.method == "POST":
        form = forms.MusicianForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        
    diction={'title':"Add Musician",'musician_form':form}
    return render(request,'first_app/musician_form.html',context=diction)
def album_form(request):
    form = forms.AlbumForm()
    if request.method == "POST":
        form = forms.AlbumForm(request.POST)
        if form.is_valid():
            form.save(commit = True)
            return index(request)
    diction={'title':"Add Album",'album_form':form}
    return render(request,'first_app/album_form.html',context=diction)

templates/first_app/album_form.html
{% extends 'first_app/base.html' %}
{% block body_block %}
 <h3>Album Form:</h3>
 <form method ="POST">
     {{album_form.as_p}}
     {% csrf_token %}
<input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
{% endblock body_block %}

templates/first_app/album_list.html
{% extends 'first_app/base.html' %}
{% block body_block %}
 <h3>Album List</h3>
{% endblock body_block %}

templates/first_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{{title}}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'first_app:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'first_app:musician_form' %}">Add Musician</a>
              </li>
            </ul>
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'first_app:album_form' %}">Add Album</a>
                </li>
              
              </ul>
            
          </div>
      
        </div>
     </nav>
     <div class="container">
      {% block body_block %}

      {% endblock body_block %}

    
     </div>

    


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/first_app/index.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<h3>List of Musician:</h3>
<ul>
    {% if musician_list %}
     {% for musician in musician_list%}
      <li>{{musician.first_name}}</li>
      <li>{{musician.last_name}}</li>
     {% endfor %}
     {% else %}
     <h4>No musician in the list</h4>
    {% endif %}
</ul>
{% endblock body_block %}

templates/first_app/musician_form.html
{% extends 'first_app/base.html' %}
{% block body_block %}
 <h3>Musician Form</h3>
 <form method="POST">
     {{musician_form.as_p}}
     {% csrf_token %}
     <input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
 </form>
{% endblock body_block %}